// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/training-plans/ai": {
            "post": {
                "description": "Stores a plan generated by the AI service. Validates exercises and assigns to user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal"
                ],
                "summary": "Create a training plan from AI (INTERNAL ONLY)",
                "parameters": [
                    {
                        "description": "AI Plan data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateTrainingPlanFromAIRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/private/nutrition-plans/generate": {
            "post": {
                "description": "Calculates macros and creates a plan based on user metrics and goals.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nutrition"
                ],
                "summary": "Generate nutritional plan",
                "parameters": [
                    {
                        "description": "Plan generation data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.GenerateNutritionPlanInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NutritionPlan"
                        }
                    }
                }
            }
        },
        "/private/training-plans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new training plan. Accessible by trainers (role 3) and regular users (role 4).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Create a training plan",
                "parameters": [
                    {
                        "description": "Plan data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateTrainingPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/private/training-plans/:id/clone": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clones an existing plan (template or other) and assigns it to a specific user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Clone a training plan for a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Plan ID to clone",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Clone data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CloneTrainingPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/private/training-plans/:id/days/:dayId/complete": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks a training day as completed or not.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Update training day progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Day ID",
                        "name": "dayId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Progress data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateDayCompletionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/private/training-plans/adapt": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Analyzes user progress and creates an adapted version of the latest plan if completion is high.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Adapt training plan based on progress",
                "responses": {}
            }
        },
        "/private/training-plans/user/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all training plans assigned to a specific user. Regular users can only query their own.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Get training plans for a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/private/training-plans/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a training plan with its days and workouts. Users can only see their assigned plans.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Get training plan by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Training Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/private/training-plans/{id}/assign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Assigns an existing training plan to a user. Only accessible by trainers (role 3).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Assign training plan to a user (TRAINER ONLY)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Training Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Assignment data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.AssignTrainingPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/private/training-plans/{id}/days": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a workout day to an existing training plan. DayNumber must be within the plan's duration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TrainingPlans"
                ],
                "summary": "Add a day to a training plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Training Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Day data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.AddTrainingDayRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/public/exercises": {
            "get": {
                "description": "Retrieve all exercises. Optionally filter by bodyPart and target.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Get list of exercises",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by body part",
                        "name": "bodyPart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by target",
                        "name": "target",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/public/exercises/import": {
            "post": {
                "description": "Fetch exercises from external API and store them locally. Highly idempotent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Manually import exercises",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/public/exercises/{id}": {
            "get": {
                "description": "Retrieve a specific exercise using its unique ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Get exercise by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/public/foods": {
            "get": {
                "description": "Retrieve a list of foods filtered by name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "Search foods",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Food name to search",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/public/foods/import": {
            "post": {
                "description": "Triggers a one-time import of basic food categories from USDA API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "Manual import of foods from USDA",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/public/foods/{id}": {
            "get": {
                "description": "Retrieve details of a specific food item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "Get food by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Food ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/public/workouts/{id}/full": {
            "get": {
                "description": "Retrieve a workout with its exercises and sets in a frontend-friendly structure.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workouts"
                ],
                "summary": "Get full workout details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.AIDayRequest": {
            "type": "object",
            "required": [
                "dayNumber",
                "workout"
            ],
            "properties": {
                "dayNumber": {
                    "type": "integer"
                },
                "workout": {
                    "$ref": "#/definitions/dtos.AIWorkoutRequest"
                }
            }
        },
        "dtos.AIExerciseRequest": {
            "type": "object",
            "required": [
                "exerciseId",
                "sets"
            ],
            "properties": {
                "exerciseId": {
                    "type": "integer"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.AISetRequest"
                    }
                }
            }
        },
        "dtos.AISetRequest": {
            "type": "object",
            "required": [
                "reps",
                "rest"
            ],
            "properties": {
                "reps": {
                    "type": "integer"
                },
                "rest": {
                    "type": "integer"
                }
            }
        },
        "dtos.AIWorkoutRequest": {
            "type": "object",
            "required": [
                "exercises",
                "name"
            ],
            "properties": {
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.AIExerciseRequest"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.AddTrainingDayRequest": {
            "type": "object",
            "required": [
                "dayNumber",
                "workoutId"
            ],
            "properties": {
                "dayNumber": {
                    "type": "integer",
                    "minimum": 1
                },
                "notes": {
                    "type": "string"
                },
                "workoutId": {
                    "type": "integer"
                }
            }
        },
        "dtos.AssignTrainingPlanRequest": {
            "type": "object",
            "required": [
                "startDate",
                "userId"
            ],
            "properties": {
                "startDate": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "dtos.CloneTrainingPlanRequest": {
            "type": "object",
            "required": [
                "targetUserId"
            ],
            "properties": {
                "targetUserId": {
                    "type": "integer"
                }
            }
        },
        "dtos.CreateTrainingPlanFromAIRequest": {
            "type": "object",
            "required": [
                "days",
                "durationDays",
                "name",
                "userId"
            ],
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.AIDayRequest"
                    }
                },
                "durationDays": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "dtos.CreateTrainingPlanRequest": {
            "type": "object",
            "required": [
                "durationDays",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "durationDays": {
                    "type": "integer",
                    "minimum": 1
                },
                "isTemplate": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateDayCompletionRequest": {
            "type": "object",
            "properties": {
                "isCompleted": {
                    "type": "boolean"
                }
            }
        },
        "models.NutritionPlan": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dailyCalories": {
                    "type": "number"
                },
                "dailyCarbs": {
                    "type": "number"
                },
                "dailyFats": {
                    "type": "number"
                },
                "dailyProtein": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "objective": {
                    "description": "e.g., weight_loss, muscle_gain, maintenance",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "usecases.GenerateNutritionPlanInput": {
            "type": "object",
            "properties": {
                "activityLevel": {
                    "description": "1.2 (sedentary) to 1.9 (heavy)",
                    "type": "number"
                },
                "age": {
                    "type": "integer"
                },
                "gender": {
                    "description": "male, female",
                    "type": "string"
                },
                "height": {
                    "description": "cm",
                    "type": "number"
                },
                "objective": {
                    "description": "weight_loss, muscle_gain, maintenance",
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "weight": {
                    "description": "kg",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
